---
- name: Patch Linux Servers
  hosts: all
  become: true  # or become_user: your_user
  gather_facts: true

  tasks:
    - name: Check for updates
      ansible.builtin.package_facts:
        manager: auto
      register: package_info

    - name: Install updates (if any)
      ansible.builtin.package:
        name: '*'
        state: latest
        update_cache: true
      when: package_info.updates is defined and package_info.updates | length > 0
      notify: Reboot system if required

    - name: Reboot the server if required
      ansible.builtin.reboot:
      name: Reboot system
      when: reboot_required.changed
      register: reboot_required

  handlers:
    - name: Reboot system if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: reboot_required.changed
